-- Root user
ALTER USER IF EXISTS 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${DB_ROOT}';
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED WITH mysql_native_password BY '${DB_ROOT}';
-- Privilèges root
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;


-- Création DB
CREATE DATABASE IF NOT EXISTS ${DB_NAME};
-- Users
CREATE USER IF NOT EXISTS '${DB_ADMIN}'@'%' IDENTIFIED BY '${DB_ADMIN_PASS}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';
-- Permissions
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_ADMIN}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ${DB_NAME}.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
-- Privilèges
GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${DB_ADMIN}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON `${DB_NAME}`.* TO '${DB_USER}'@'%';


-- Finalisation
FLUSH PRIVILEGES;
